import { QuizStep } from './types';

export const QUIZ_STEPS: QuizStep[] = [
  {
    id: 1,
    type: 'question',
    title: 'Empezamos',
    subtitle: 'Elige tu edad abajo:',
    options: [
      { id: '18-29', text: '18-29' },
      { id: '29-39', text: '29-39' },
      { id: '39-49', text: '39-49' },
      { id: '50+', text: '50+' },
    ],
    progressPercent: 5,
  },
  {
    id: 2,
    type: 'question',
    title: '¿Cuál es el nivel de caída de tus senos?',
    subtitle: 'Toca la opción de abajo.',
    options: [
      { id: 'grado1', text: 'Grado I' },
      { id: 'grado2', text: 'Grado II' },
      { id: 'grado3', text: 'Grado III' },
    ],
    progressPercent: 10,
  },
  {
    id: 3,
    type: 'question',
    title: '¿Cuál es tu principal objetivo?',
    subtitle: 'Toca la opción de abajo',
    options: [
      { id: 'autoestima', text: 'Aumentar la autoestima', icon: '😊' },
      { id: 'pareja', text: 'Mejorar la relación con mi pareja', icon: '💋' },
      { id: 'escote', text: 'Usar escotes y bikinis sin sentir vergüenza', icon: '👙' },
    ],
    progressPercent: 15,
  },
  {
    id: 4,
    type: 'question',
    title: '¿Cuál es su tipo de cuerpo?',
    subtitle: 'Toca la option de abajo',
    options: [
      { id: 'delgada', text: 'Delgada' },
      { id: 'normal', text: 'Normal' },
      { id: 'sobrepeso', text: 'Con Sobrepeso' },
    ],
    progressPercent: 20,
  },
  {
    id: 5,
    type: 'info',
    title: '147 mil mujeres',
    description: 'Ya hemos ayudado a más de 147 mil mujeres en todo el mundo, vamos a dar lo mejor para ayudarte a alcanzar tus objetivos.',
    buttonText: 'Continuar',
    progressPercent: 25,
  },
  {
    id: 6,
    type: 'question',
    title: '¿Actualmente está usted amamantando?',
    options: [
      { id: 'si', text: 'Sí, estoy amamantando.' },
      { id: 'no', text: 'No estoy amamantando.' },
    ],
    progressPercent: 30,
  },
  {
    id: 7,
    type: 'question',
    title: '¿Utilizas algún método anticonceptivo?',
    options: [
      { id: 'si_tomo', text: 'Sí, tomo' },
      { id: 'si_tome', text: 'Sí, tomé pero ya no tomo' },
      { id: 'no', text: 'No, no tomo' },
    ],
    progressPercent: 35,
  },
  {
    id: 8,
    type: 'info',
    title: '"¡El uso prolongado de anticonceptivos destruirá tus senos para siempre!"',
    description: 'Medicamentos como los anticonceptivos pueden contribuir a la Ptosis Mamaria, afectando la musculatura del seno de forma acelerada, causando caída, flacidez y sensación de envejecimiento del mismo.',
    buttonText: 'Continuar',
    progressPercent: 40,
  },
  {
    id: 9,
    type: 'question',
    title: '¿Has oído hablar de los músculos ptosis mamarios?',
    options: [
      { id: 'si', text: 'Sí', icon: '👍' },
      { id: 'no', text: 'No', icon: '👎' },
    ],
    statusText: 'Esto es muy importante. Los músculos ptosis mamarios son la principal causa de problemas relacionados con la caída de los senos.',
    progressPercent: 45,
  },
  {
    id: 10,
    type: 'info',
    title: 'El suelo pélvico mamario es el secreto para levantar los senos.',
    description: 'El fortalecimiento de estos 3 grupos elimina la caída, flacidez, restaura la salud de los senos y los deja con un aspecto "erguido y durito".',
    statusText: 'Continúa respondiendo. Vamos a mostrarte ejercicios e información para fortalecer este grupo muscular.',
    buttonText: 'Continuar',
    progressPercent: 55,
  },
  {
    id: 11,
    type: 'question',
    title: '¿Practicas algún tipo de actividad física hoy?',
    subtitle: 'Caminata, gimnasio, carrera...',
    options: [
      { id: 'todos', text: 'Sí, todos los dias' },
      { id: 'algunas', text: 'Sí, algunas veces a la semana' },
      { id: 'pocas', text: 'Sí, pocas veces a la semana' },
      { id: 'raramente', text: 'Raramente hago ejercicio' },
      { id: 'no', text: 'No hago ejercicio' },
    ],
    progressPercent: 65,
  },
  {
    id: 12,
    type: 'info',
    title: '¡Fortalecer el suelo mamario es simple!',
    description: 'Solo necesitas realizar ejercicios específicos y en 21 días estarás transformada.',
    buttonText: 'Continuar',
    progressPercent: 75,
  },
  {
    id: 13,
    type: 'question',
    title: 'Necesitamos solo un poco más de información',
    subtitle: '¿Cómo evalúas la calidad de tu alimentación hoy?',
    options: [
      { id: 'excelente', text: '¡Excelente!', icon: '🥗' },
      { id: 'normal', text: 'Normal', icon: '🥪' },
      { id: 'pesima', text: 'Pésima', icon: '🍔' },
    ],
    progressPercent: 85,
  },
  {
    id: 14,
    type: 'loading',
    title: 'Estamos examinando sus respuestas...',
    statusText: 'Analizando tu perfil en base a tus respuestas...',
    progressPercent: 90,
  },
  {
    id: 15,
    type: 'score',
    title: 'Nivel de aptitud',
    description: '¡Aprobada!',
    progressPercent: 95,
    buttonText: 'Continuar',
  },
  {
    id: 16,
    type: 'carousel',
    title: 'Mira algunos resultados',
    subtitle: 'Desliza hacia el lado para ver más resultados',
    options: [
      { id: 'res1', text: 'Antes' },
      { id: 'res2', text: 'Después' },
    ],
    buttonText: 'Continuar',
    progressPercent: 98,
  },
  {
    id: 17,
    type: 'question',
    title: '¿Qué harías hoy si tuvieras senos nuevos?',
    options: [
      { id: 'noche', text: 'Tendría una noche muy especial con mi pareja' },
      { id: 'escote', text: 'Me pondría un súper escote para salir y celebrar' },
      { id: 'bikini', text: 'Me pondría un bikini e iría directo a la playa' },
      { id: 'espejo', text: 'Pasaría horas admirándome en el espejo' },
    ],
    progressPercent: 99,
  },
  {
    id: 18,
    type: 'question',
    title: '¿Estás lista para seguir un plan práctico?',
    options: [
      { id: 'listo', text: 'Sí, estoy lista', icon: '🔥' },
      { id: 'saber', text: 'Quiero saber más...', icon: '🤔' },
    ],
    progressPercent: 100,
  },
];
